spring:
    application:
        name: MySQL
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.99.18.99/microService   
        
server:
    port: 8762
    
security:
    user:
        name: admin
        password: secret

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

    
        